colorscheme red-phoenix

set-option global ui_options ncurses_assistant=cat

set global tabstop 2
set global indentwidth 2

# replace tab with spaces
hook global InsertChar \t %{ exec -draft -itersel h@ }

hook global BufCreate .*/*.mk %{
  set-option buffer filetype makefile
}

hook global WinSetOption filetype=haskell %{
  set window lintcmd 'hlint'
  add-highlighter global column 80 default,rgb:404040
  add-highlighter global column 120 default,rgb:565656
}

hook global WinSetOption filetype=makefile %{
  set buffer indentwidth 0
}

hook global WinSetOption filetype=markdown %{
  add-highlighter global wrap -word
}

hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_reg_dquote" | xsel --input --clipboard
}}

map global user P '!xsel --output --clipboard<ret>' -docstring 'paste (above) from clipboard'
map global user p '<a-!>xsel --output --clipboard<ret>' -docstring 'paste (below) from clipboard'
map global user w %{:echo "Word Count:" %sh{wc -w <lt><lt><lt> "${kak_selection}"}<ret>} -docstring 'show selected word count'

map global normal <space> , -docstring 'leader'
map global normal <backspace> <space> -docstring 'remove all sels except main'

def find -params 1 -shell-candidates %{ find -type f } %{ edit %arg{1} }

def git-edit -params 1 -shell-candidates %{ git ls-files } %{ edit %arg{1} }
